name: rubocop-challenger

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.7.6
      - run: git config remote.origin.url "git@github.com:${GITHUB_REPOSITORY}.git"
      - run: gem install rubocop_challenger
      - run: rubocop_challenger go --email=rubocop-challenger@example.com --name="Rubocop Challenger"
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
